version: '3'
services:
  mongo:
    image: mongo:4.0
    container_name: mongo
    ports:
      - "27017:27017"
  talentmatch-server:
    build:
      context: ./server
    container_name: talentmatch-server
    ports:
      - "80:80"
    volumes:
      - ./server:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
  talentmatch-debug:
    build:
      context: ./debug
    container_name: talentmatch-debug
    volumes:
      - ./debug:/app
      - debug_node_modules:/app/node_modules
volumes:
  mongo-data:
  node_modules:
  debug_node_modules: