openapi: 3.0.0
info:
  title: Gachitda API
  version: 1.0.0

paths:
  /api/auth/email:
    post:
      tags:
        - MailVerification
      summary: 이메일 인증 요청
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                email:
                  type: string
                  format: email
                  example: user@example.ac.kr
      responses:
        '200':
          description: Verification email sent successfully
        '400':
          description: Invalid request - missing or invalid accessToken or email
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                invalid_request:
                  value:
                    error: INVALID_REQUEST
                invalid_email:
                  value:
                    error: INVALID_EMAIL
                invalid_access_token:
                  value:
                    error: INVALID_ACCESS_TOKEN
        '500':
          description: Internal server error - failed to send email
  /api/auth/email/verify:
    post:
      tags:
        - MailVerification
      summary: 이메일 인증 코드 확인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                code:
                  type: string
      responses:
        '200':
          description: 인증 코드 확인 성공
        '400':
          description: Invalid request - missing or invalid accessToken or code
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                invalid_request:
                  value:
                    error: INVALID_REQUEST
                invalid_code:
                  value:
                    error: INVALID_CODE
        '422':
          description: Verification code expired or no verification in progress
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                code_expired:
                  value:
                    error: CODE_EXPIRED
                no_verification_pending:
                  value:
                    error: NO_VERIFICATION_PENDING
  /api/noti/subscription:
    post:
      tags:
        - Subscription
      summary: 웹 알림 허용
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                subscription:
                  type: object
      responses:
        '200':
          description: 구독 저장 성공
        '400':
          description: 잘못된 액세스 토큰
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: INVALID_ACCESS_TOKEN

  /api/noti/sendpush:
    post:
      tags:
        - Subscription
      summary: 웹 알림 전송
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                text:
                  type: string
      responses:
        '200':
          description: 푸시 알림 전송 성공
        '400':
          description: 잘못된 액세스 토큰
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: INVALID_ACCESS_TOKEN
  /api/auth/access-token:
    get:
      tags:
        - AccessToken
      summary: Access Token 발급
      parameters:
        - in: header
          name: Cookie
          schema:
            type: string
          required: true
          example: refreshtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDI2NzM3NDc0NywiaWF0IjoxNzQ3NzI3NzU4LCJleHAiOjE3NTAzMTk3NTh9.mCwFrDh6-tjQ4JxKAgUdtXV89Lp3FZ5sZbu4aiRP56E
      responses:
        '200':
          description: Access Token 발급 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: 재 로그인 필요
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                no_refresh_token:
                  value:
                    error: NO_REFRESH_TOKEN
                invalid_refresh_token:
                  value:
                    error: INVALID_REFRESH_TOKEN
